development: &default
  adapter: mysql2
  username: root
  password:
  database: stallone_development
  host: mysql-server

test: &test
  <<: *default
  database: stallone_test

cucumber:
  <<: *test
