development: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: product-catalog_development
  pool: 5
  username: root
  password:
  host: db

test: &test
  <<: *default
  database: product-catalog_test