development: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: product_catalog_development
  pool: 5
  username: root
  password:
  host: mysql-server

test: &test
  <<: *default
  database: product_catalog_test
